'use client';

import React from 'react';

interface ArchitectureDocumentProps {
  markdown: string;
}

export function ArchitectureDocument({ markdown }: ArchitectureDocumentProps) {
  // A basic markdown parser for the specific headers generated by the AI flow
  const renderContent = () => {
    const lines = markdown.split('\n');
    const elements: React.ReactNode[] = [];
    let currentList: string[] = [];
    let isCodeBlock = false;
    let codeContent = '';

    const flushList = (key: string) => {
      if (currentList.length > 0) {
        elements.push(
          <ul key={`list-${key}`}>
            {currentList.map((item, idx) => (
              <li key={`li-${key}-${idx}`}>{item.replace(/^- /, '')}</li>
            ))}
          </ul>
        );
        currentList = [];
      }
    };

    lines.forEach((line, index) => {
      if (line.startsWith('```')) {
        if (isCodeBlock) {
          elements.push(
            <pre key={`code-${index}`} className="bg-background/80 p-4 rounded-md border border-border my-4 overflow-x-auto text-sm font-code">
              <code>{codeContent}</code>
            </pre>
          );
          codeContent = '';
          isCodeBlock = false;
        } else {
          isCodeBlock = true;
        }
        return;
      }

      if (isCodeBlock) {
        codeContent += line + '\n';
        return;
      }

      if (line.startsWith('# ')) {
        flushList(String(index));
        elements.push(<h1 key={index}>{line.replace('# ', '')}</h1>);
      } else if (line.startsWith('## ')) {
        flushList(String(index));
        elements.push(<h2 key={index}>{line.replace('## ', '')}</h2>);
      } else if (line.startsWith('### ')) {
        flushList(String(index));
        elements.push(<h3 key={index}>{line.replace('### ', '')}</h3>);
      } else if (line.startsWith('- ')) {
        currentList.push(line);
      } else if (line.trim()) {
        flushList(String(index));
        elements.push(<p key={index}>{line}</p>);
      }
    });

    flushList('end');
    return elements;
  };

  return (
    <div className="animate-fade-in">
      {renderContent()}
    </div>
  );
}
